[package]
name = "kyonos"
version = "0.1.0"
edition = "2024"
authors = ["steven-jaro <jaromersen@gmail.com>"]

[dependencies]
bootloader = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
